[package]
name = "ocl-test"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
ocl = "0.19.7"
polars = {version = "0.46.0", features = ["lazy", "parquet"]}
rayon = "1.10.0"
regex = "1.11.1"
